baseURL = 'https://stderr.me/'
languageCode = 'en-us'
title = 'stderr.me'
theme = 'PaperMod'

[params]
description = "Systems programming, low-level adventures, figuring stuff out"
author = "Neel"

[params.homeInfoParams]
Title = "Hi, I'm Neel"
Content = "This is a log of my adventures in systems programming and other development stuff"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2
